### ISSUE TITLE
browser-source shows 1 column 

### ISSUE THREAD

**Issue by MancerMaik** [thoanny/streamelements-pixels-war#1]
This Widget works fine in Streamelements and in Browser Preview but...

when i add it to obs 27.2.4 as new browser source and add the URL preview link and set it to 1920x1080 (same as streamelements) it appears with only 1 column.

Any clues how to fix that?
First time i see a widget preview is different then the browser source. 

![1column](https://user-images.githubusercontent.com/108303141/192675953-e4a36d6e-255e-4133-98a3-4eedb7d9abce.png)

**Comment by thoanny** [comment]
Solution: upgraded OBS from 27.2.4 to 28.*
